services:
  job-board:
    image: job-board
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
      target: build
    command: npm run start:dev
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - ..:/app
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
